name: "LLM Agent Trust Verification"
description: "Professional LLM security scanner for GitHub Actions. Automatically detect API key exposure, rate limiting gaps, and input validation issues."
author: "Liam Ballesty"
branding:
  icon: shield
  color: purple

inputs:
  config:
    description: "Path to llm-policy.yml configuration file"
    required: false
    default: "llm-policy.yml"

outputs:
  status:
    description: "Overall status: passed, warning, or failed"
  api-key-violations:
    description: "Number of API key violations found"
  rate-limit-warnings:
    description: "Number of rate limit warnings"
  input-sanitize-warnings:
    description: "Number of input sanitization warnings"
  badge-status:
    description: "Status text for badges: ✅ Secured, ⚠️ Warnings, or ❌ Failed"

runs:
  using: "docker"
  image: "Dockerfile"
