name: "LLM Agent Trust Verification"
description: "Scans for leaked LLM API keys, missing rate-limit incursions, and preforms input sanitization checks."
author: "Liam Ballesty"
branding:
  icon: shield
  color: purple

inputs:
  config:
    description: "Path to llm-policy.yml (optional)"
    required: false
    default: "llm-policy.yml"

runs:
  using: "docker"
  image: "Dockerfile"
