name: "LLM Agent Trust Verification"
description: "Scans for leaked LLM API keys, missing rate-limit incursions, and preforms input sanitization checks."
author: "Liam Ballesty"
branding:
  icon: shield
  color: purple

outputs:
  status:
    description: "Overall status: passed, warning, or failed"
  api-key-violations:
    description: "Number of API key violations found"
  rate-limit-warnings:
    description: "Number of rate limit warnings"
  input-sanitize-warnings:
    description: "Number of input sanitization warnings"
  badge-status:
    description: "Status text for badges"

runs:
  using: "docker"
  image: "Dockerfile"
