name: "LLM Agent Trust Verification"
description: "Professional LLM security scanner. Automatically detect API key exposure, rate limiting gaps, and input validation issues."
author: "Liam Ballesty"
branding:
  icon: shield
  color: purple

inputs:
  config:
    description: "Path to llm-policy.yml configuration file"
    required: false
    default: "llm-policy.yml"

outputs:
  status:
    description: "Overall status: passed, warning, or failed"
  api-key-violations:
    description: "Number of API key violations found"
  rate-limit-warnings:
    description: "Number of rate limit warnings"
  input-sanitize-warnings:
    description: "Number of input sanitization warnings"
  badge-status:
    description: "Status text for badges: ✅ Secured, ⚠️ Warnings, or ❌ Failed"

  # V1 Agent Verification Outputs
  agent-status:
    description: "Agent verification status: verified, trusted, validated, basic, unverified, or error"
  agent-trust-score:
    description: "Agent trust score (0.0 to 1.0)"
  agent-id:
    description: "Unique agent identifier (DID format)"
  agent-badge-status:
    description: "Agent badge status with emoji and trust level"
  agent-verification-url:
    description: "URL for agent verification details"

runs:
  using: "docker"
  image: "Dockerfile"
